[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

# Run reminder check every 10 minutes
[[scheduled.functions]]
  name = "check-reminders"
  cron = "*/10 * * * *"
